### ISSUE TITLE
.whl not working

### ISSUE THREAD

**Issue by mehreenjabeen** [nknytk/built-onnxruntime-for-raspberrypi-linux#3]
Hi,

I tried to install the provided .whl on my rpi 3 model B+ using the beow command: 
_pip install onnxruntime-1.4.0-cp38-cp38-linux_armv7l.whl_
I got the below error: _onnxruntime-1.4.0-cp38-cp38-linux_armv7l.whl is not a supported wheel on this platform._
My python version is  3.7.3 and pip version is pip 21.1.3

Can you suggest something what might be the issue?

**Comment by nknytk** [comment]
Could you try `pip install onnxruntime-1.8.0-cp37-cp37m-linux_armv7l.whl` ? The files with _cp37_ is whl for Python3.7, and I recommend you to use newer version.

**Comment by mehreenjabeen** [comment]
yes, it worked . Thanks a lot. Your wheels saved my time. 
Although I got _succesfully installed onnxruntime_ , upon importing onnxruntime I am getting _/home/pi/.local/lib/python3.5/site-packages/onnxruntime/capi/onnxruntime_validation.py:22: UserWarning: Unsupported architecture (32bit). ONNX Runtime supports 64bit architecture, only.
  warnings.warn('Unsupported architecture (%s). ONNX Runtime supports 64bit architecture, only.' % __my_arch__)_

Is onnxruntime meant for 64-bit systems only?

**Comment by mehreenjabeen** [comment]
closing the issue as despite the warning that pops up, I am able to proceed.
