### ISSUE TITLE
Debian Bookworm support

### ISSUE THREAD

**Issue by goldyfruit** [nknytk/built-onnxruntime-for-raspberrypi-linux#6]
Hi,

Do you have any plan to support Debian Bookworm (12) and so Python 3.11?

Thanks for your work.

**Comment by DrAlexLiu** [comment]
I also have the same issue. And since this issue is closed without any feedback, may I know how to solve it?

**Comment by goldyfruit** [comment]
I closed it because I will wait until 3.12 being supported officially by Microsoft.

**Comment by DrAlexLiu** [comment]
May I ask where is the link for download the x32 wheel package?

when I run the following:
sudo /opt/python3.11/bin/pip3.11 install onnxruntime

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

Also, when I goes to onnxruntime github release page, it does not have x32 binary package for downloading. 

Thanks.

**Comment by goldyfruit** [comment]
There is no 32-bit version available anymore.

**Comment by DrAlexLiu** [comment]
@goldyfruit 
I have complied onnxruntime 1.17.1 using my RPi5. 
Do you still need it?

I can give you the general method or whl file.

**Comment by DrAlexLiu** [comment]
I will create a new repo and put the new whl to this, since the author of this repo has not updated for a while. 

https://github.com/DrAlexLiu/built-onnxruntime-for-raspberrypi-linux/blob/main/wheels/bookworm/onnxruntime-1.17.1-cp311-cp311-linux_armv7l.whl

**Comment by goldyfruit** [comment]
> @goldyfruit I have complied onnxruntime 1.17.1 using my RPi5. Do you still need it?
> 
> I can give you the general method or whl file.

Yes please, I would be interested by the method to build the WHL file.

**Comment by DrAlexLiu** [comment]
@goldyfruit 

The method is here:

https://github.com/DrAlexLiu/built-onnxruntime-for-raspberrypi-linux/blob/main/README.md
Let me know if you need more help.

**Comment by goldyfruit** [comment]
> @goldyfruit
> 
> The method is here:
> 
> https://tgithub.com/DrAlexLiu/built-onnxruntime-for-raspberrypi-linux/blob/main/README.mdt Let me know if you need more help.

Your link is wrong, like phishing :D

Link: https://github.com/DrAlexLiu/built-onnxruntime-for-raspberrypi-linux/blob/main/README.md

**Comment by DrAlexLiu** [comment]
Sorry, don't know why there is a t overthere. 

I am using docker to cross compile the onnxruntime, which is faster than on Pi. I will let you know when it is proved to be working.
